# Generated by Django 5.2.3 on 2025-06-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Management_System', '0002_registrationmodel_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
