# Generated by Django 5.2.3 on 2025-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Management_System', '0005_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
