# Generated by Django 5.2.3 on 2025-06-20 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Management_System', '0006_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Management_System.registrationmodel'),
        ),
    ]
