# Generated by Django 5.2.3 on 2025-06-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Management_System', '0007_alter_events_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='event',
            new_name='Organization_name',
        ),
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='registrationmodel',
            name='date',
        ),
    ]
