# Generated by Django 5.2.3 on 2025-06-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Management_System', '0008_rename_event_registrationmodel_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
